import { P2PAdvertisement, P2PMerchant, P2PAsset, PaymentMethodInfo } from "./types";

export const ASSETS: P2PAsset[] = [
  { symbol: "USDT", name: "Tether", icon: "₮", decimals: 6, status: "active" },
  { symbol: "BTC", name: "Bitcoin", icon: "₿", decimals: 8, status: "active" },
  { symbol: "ETH", name: "Ethereum", icon: "Ξ", decimals: 18, status: "active" },
  { symbol: "USDC", name: "USD Coin", icon: "$", decimals: 6, status: "active" },
  { symbol: "SOL", name: "Solana", icon: "◎", decimals: 9, status: "active" },
];

export const FIAT_CURRENCIES = [
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
];

export const PAYMENT_METHODS: PaymentMethodInfo[] = [
  { id: "bank_transfer", name: "Bank Transfer", icon: "🏦", currency: ["USD", "EUR", "GBP"], enabled: true },
  { id: "zelle", name: "Zelle", icon: "💸", currency: ["USD"], enabled: true },
  { id: "paypal", name: "PayPal", icon: "🅿️", currency: ["USD", "EUR", "GBP"], enabled: true },
  { id: "wise", name: "Wise", icon: "🦉", currency: ["USD", "EUR", "GBP", "AED"], enabled: true },
  { id: "revolut", name: "Revolut", icon: "💳", currency: ["USD", "EUR", "GBP"], enabled: true },
  { id: "cash_app", name: "Cash App", icon: "💵", currency: ["USD", "GBP"], enabled: true },
  { id: "sepa", name: "SEPA", icon: "🇪🇺", currency: ["EUR"], enabled: true },
];

export const MOCK_MERCHANTS: P2PMerchant[] = [
  {
    id: "m_101",
    username: "CryptoKing",
    displayName: "CryptoKing",
    verified: true,
    online: true,
    completionRate: 98.7,
    totalOrders: 1245,
    averageReleaseTime: 4.2,
    positiveFeedback: 1230,
    negativeFeedback: 15,
    joinedAt: "2023-01-15T00:00:00Z",
    supportedPaymentMethods: ["bank_transfer", "zelle", "wise"],
    badge: "verified"
  },
  {
    id: "m_102",
    username: "FastTraderUS",
    displayName: "FastTraderUS",
    verified: true,
    online: true,
    completionRate: 99.5,
    totalOrders: 8930,
    averageReleaseTime: 2.1,
    positiveFeedback: 8890,
    negativeFeedback: 40,
    joinedAt: "2022-05-10T00:00:00Z",
    supportedPaymentMethods: ["zelle", "cash_app"],
    badge: "top_merchant"
  },
  {
    id: "m_103",
    username: "GlobalExchange",
    displayName: "GlobalExchange",
    verified: false,
    online: false,
    completionRate: 94.2,
    totalOrders: 412,
    averageReleaseTime: 12.5,
    positiveFeedback: 388,
    negativeFeedback: 24,
    joinedAt: "2023-11-20T00:00:00Z",
    supportedPaymentMethods: ["paypal", "wise", "revolut"],
    badge: "trusted"
  },
  {
    id: "m_104",
    username: "SatoshiStacker",
    displayName: "SatoshiStacker",
    verified: true,
    online: true,
    completionRate: 97.8,
    totalOrders: 2156,
    averageReleaseTime: 5.5,
    positiveFeedback: 2100,
    negativeFeedback: 56,
    joinedAt: "2021-08-01T00:00:00Z",
    supportedPaymentMethods: ["bank_transfer", "sepa"],
    badge: "verified"
  }
];

// Generate robust mock advertisements
export const MOCK_ADVERTISEMENTS: P2PAdvertisement[] = [
  // USDT - SELL (User buys from merchant)
  {
    id: "ad_1",
    merchantId: "m_102",
    side: "sell", // Merchant is selling, User is buying
    asset: "USDT",
    fiat: "USD",
    price: 1.005,
    priceType: "fixed",
    availableAmount: 15000,
    minLimit: 50,
    maxLimit: 2000,
    paymentMethods: ["zelle", "cash_app"],
    completionRate: 99.5,
    completedOrders: 8930,
    responseTimeMinutes: 1,
    merchantOnline: true,
    merchantVerified: true,
    terms: "Fast release. No third party payments. Must include order number in memo.",
    status: "online",
    createdAt: "2024-03-01T10:00:00Z"
  },
  {
    id: "ad_2",
    merchantId: "m_101",
    side: "sell",
    asset: "USDT",
    fiat: "USD",
    price: 1.01,
    priceType: "fixed",
    availableAmount: 50000,
    minLimit: 500,
    maxLimit: 10000,
    paymentMethods: ["bank_transfer", "wise"],
    completionRate: 98.7,
    completedOrders: 1245,
    responseTimeMinutes: 5,
    merchantOnline: true,
    merchantVerified: true,
    terms: "Verified users only. Bank transfer must match KYC name.",
    status: "online",
    createdAt: "2024-03-05T12:00:00Z"
  },
  {
    id: "ad_3",
    merchantId: "m_103",
    side: "sell",
    asset: "USDT",
    fiat: "USD",
    price: 1.03,
    priceType: "fixed",
    availableAmount: 500,
    minLimit: 10,
    maxLimit: 500,
    paymentMethods: ["paypal"],
    completionRate: 94.2,
    completedOrders: 412,
    responseTimeMinutes: 15,
    merchantOnline: false,
    merchantVerified: false,
    terms: "PayPal Friends and Family only.",
    status: "online",
    createdAt: "2024-03-10T14:00:00Z"
  },
  
  // USDT - BUY (User sells to merchant)
  {
    id: "ad_4",
    merchantId: "m_102",
    side: "buy", // Merchant is buying, User is selling
    asset: "USDT",
    fiat: "USD",
    price: 0.995,
    priceType: "fixed",
    availableAmount: 25000,
    minLimit: 100,
    maxLimit: 5000,
    paymentMethods: ["zelle", "bank_transfer"],
    completionRate: 99.5,
    completedOrders: 8930,
    responseTimeMinutes: 2,
    merchantOnline: true,
    merchantVerified: true,
    terms: "Will send funds immediately. Honest trader.",
    status: "online",
    createdAt: "2024-03-02T10:00:00Z"
  },
  {
    id: "ad_5",
    merchantId: "m_101",
    side: "buy",
    asset: "USDT",
    fiat: "USD",
    price: 0.99,
    priceType: "fixed",
    availableAmount: 100000,
    minLimit: 1000,
    maxLimit: 50000,
    paymentMethods: ["bank_transfer", "wise"],
    completionRate: 98.7,
    completedOrders: 1245,
    responseTimeMinutes: 10,
    merchantOnline: true,
    merchantVerified: true,
    terms: "Large blocks only. Reliable liquidity provider.",
    status: "online",
    createdAt: "2024-03-04T12:00:00Z"
  },

  // BTC - SELL (User buys from merchant)
  {
    id: "ad_6",
    merchantId: "m_104",
    side: "sell",
    asset: "BTC",
    fiat: "USD",
    price: 68500,
    priceType: "floating",
    availableAmount: 2.5,
    minLimit: 100,
    maxLimit: 10000,
    paymentMethods: ["bank_transfer"],
    completionRate: 97.8,
    completedOrders: 2156,
    responseTimeMinutes: 8,
    merchantOnline: true,
    merchantVerified: true,
    terms: "Standard verification required. Release upon clearing.",
    status: "online",
    createdAt: "2024-03-01T08:00:00Z"
  },
  {
    id: "ad_7",
    merchantId: "m_102",
    side: "sell",
    asset: "BTC",
    fiat: "USD",
    price: 69000,
    priceType: "fixed",
    availableAmount: 0.5,
    minLimit: 50,
    maxLimit: 2000,
    paymentMethods: ["zelle", "cash_app"],
    completionRate: 99.5,
    completedOrders: 8930,
    responseTimeMinutes: 1,
    merchantOnline: true,
    merchantVerified: true,
    terms: "Instant release with Zelle.",
    status: "online",
    createdAt: "2024-03-02T09:00:00Z"
  },

  // BTC - BUY (User sells to merchant)
  {
    id: "ad_8",
    merchantId: "m_104",
    side: "buy",
    asset: "BTC",
    fiat: "USD",
    price: 67800,
    priceType: "floating",
    availableAmount: 5.0,
    minLimit: 500,
    maxLimit: 25000,
    paymentMethods: ["bank_transfer"],
    completionRate: 97.8,
    completedOrders: 2156,
    responseTimeMinutes: 12,
    merchantOnline: true,
    merchantVerified: true,
    terms: "Send BTC, get USD wire same day.",
    status: "online",
    createdAt: "2024-03-03T10:00:00Z"
  },

  // ETH - SELL (User buys from merchant)
  {
    id: "ad_9",
    merchantId: "m_101",
    side: "sell",
    asset: "ETH",
    fiat: "USD",
    price: 3600,
    priceType: "fixed",
    availableAmount: 15.0,
    minLimit: 100,
    maxLimit: 5000,
    paymentMethods: ["bank_transfer", "wise"],
    completionRate: 98.7,
    completedOrders: 1245,
    responseTimeMinutes: 4,
    merchantOnline: true,
    merchantVerified: true,
    terms: "Fast and secure.",
    status: "online",
    createdAt: "2024-03-06T11:00:00Z"
  },
  
  // SOL - SELL (User buys from merchant)
  {
    id: "ad_10",
    merchantId: "m_102",
    side: "sell",
    asset: "SOL",
    fiat: "USD",
    price: 150,
    priceType: "fixed",
    availableAmount: 200.0,
    minLimit: 20,
    maxLimit: 1000,
    paymentMethods: ["zelle", "cash_app"],
    completionRate: 99.5,
    completedOrders: 8930,
    responseTimeMinutes: 1,
    merchantOnline: true,
    merchantVerified: true,
    terms: "Instant SOL release.",
    status: "online",
    createdAt: "2024-03-07T12:00:00Z"
  }
];
