name = "api"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ethsltd_db"
database_id = "3e91dec1-5e94-434a-9697-7a9217592afe"
migrations_dir = "../../database/migrations"
